site_name: Ex.forma
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
    accent: amber
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - mkdocs-jupyter
nav:
    - Home: index.md
    - Imprint: imprint.md
